apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Changed from ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
  template:
    metadata:
      labels:
        app: combined-app
    spec:
      containers:
      - name: container1
        image: us-central1-docker.pkg.dev/k8s-assignment-454517/kubernetes-assignment/container1:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-data
          mountPath: /mency_PV_dir
      - name: container2
        image: us-central1-docker.pkg.dev/k8s-assignment-454517/kubernetes-assignment/container2:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: shared-data
          mountPath: /mency_PV_dir
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  type: LoadBalancer
  selector:
    app: combined-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  selector:
    app: combined-app
  ports:
  - port: 8081
    targetPort: 8081
