apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: us-central1-docker.pkg.dev/kubernetes-assignment-454505/kubernetes-assignment/container1:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-data
          mountPath: /mency_PV_dir
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: my-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/kubernetes-assignment-454505/kubernetes-assignment/container2:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: shared-data
          mountPath: /mency_PV_dir
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  type: LoadBalancer
  selector:
    app: container1
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  selector:
    app: container2
  ports:
  - port: 8081
    targetPort: 8081
